{"name": "Создание питомца с невалидным id за границами валидации", "status": "failed", "statusDetails": {"message": "AssertionError: assert 500 == 405\n +  where 500 = <Response [500]>.status_code", "trace": "api_client = <petstore_api_client.petstore_api_client.PetstoreApiClient object at 0x734c9c2a4e90>\n\n    @allure.title(\"Создание питомца с невалидным id за границами валидации\")\n    def test_create_pet_with_invalid_id(api_client):\n        data = PetModel(id=INVALID_ID_VALUE, name=\"cat\", photoUrls=[])\n        response = api_client.create_pet(data=dict(data))\n>       assert response.status_code == 405\nE       assert 500 == 405\nE        +  where 500 = <Response [500]>.status_code\n\ntests/test_api_pets.py:57: AssertionError"}, "start": 1724871075145, "stop": 1724871075685, "uuid": "ce03e5ae-f58b-4f3c-9368-16f792d77b4c", "historyId": "4dfb53faef2c59bbc11447b3b5ed2b41", "testCaseId": "4dfb53faef2c59bbc11447b3b5ed2b41", "fullName": "tests.test_api_pets#test_create_pet_with_invalid_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_pets"}, {"name": "host", "value": "ASUSLaptop-X509FA"}, {"name": "thread", "value": "106676-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_pets"}]}